Fix ESlint errors
gama-group/gama-backend pull request #22
Opened 2021-05-26 19:34 UTC by gustavo4passos

2021-05-26 21:13 UTC, igooralm192 requested changes

2021-05-26 21:13 UTC, igooralm192 commented on README.md
> +        "company name": contractor.companyName,
Corrigir espaço no atributo

2021-05-26 21:13 UTC, igooralm192 commented on README.md
> +        "company name": contractor.companyName,
Corrigir espaço no atributo

2021-05-26 21:13 UTC, igooralm192 commented on README.md
> +        "method of contact": process.methodOfContact,
Corrigir espaço no atributo

2021-05-31 20:50 UTC, danisan360 approved these changes
👌👌👌

2021-05-31 21:19 UTC, merged